WestWindWatch/WestWindWebApp/Pages/Categories/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WestwindSystem.BLL; // for CategoryServices
using WestwindSystem.Entities; // for Category

namespace WestWindWebApp.Pages.Categories
{
    public class IndexModel : PageModel
    {
        #region use dependecy injection to assign value to categoryServices
        private readonly CategoryServices _categoryServices;

        public IndexModel(CategoryServices categoryServices)
        {
            _categoryServices = categoryServices;
        }
        #endregion

        #region
        public List<Category> CategoryList { get; set; } = new();
        #endregion

        public void OnGet()
        {
            CategoryList = _categoryServices.Category_List();
        }
    }
}

WestWindWatch/WestWindWebApp/Pages/Categories/QueryById.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WestwindSystem.BLL; // for CategoryServices
using WestwindSystem.Entities; // for Category

namespace WestWindWebApp.Pages.Categories
{
    public class QueryByIdModel : PageModel
    {
        // Define a readonly field for CategoryServices
        private readonly CategoryServices _categoryServices;

        // Define greedy constructor with a CategoryServices that is injected by the Backend extension
        public QueryByIdModel(CategoryServices categoryServices)
        {
            _categoryServices = categoryServices;
        }

        //Define an auto-implemented property for feedback messages
        [TempData]
        public string FeedbackMessage { get; set; }

        //Define an auto-implemented property for the search value
        [BindProperty(SupportsGet = true)] // allow this property to matched to a route
        public int searchId { get; set; }

        //Define an auto-implemented property for the search result
        public Category searchSingleResult { get; set; }

        public void OnGet()
        {
            if(searchId > 0)
            {
                searchSingleResult = _categoryServices.Category_GetById(searchId);
                if (searchSingleResult == null)
                {
                    FeedbackMessage = $"No result returned for Category id. {searchId}";
                }
                else
                {
                    FeedbackMessage = $"<tr><td>{searchSingleResult.CategoryId}</td>" +
                        $"<td>{searchSingleResult.CategoryName} </td>" +
                        $"<td>{searchSingleResult.Description}</td></tr> ";
                }
            }
        }
        public IActionResult OnPostFetch()
        {
            //Check if the search value is valid
            if (searchId <= 0)
            {
                FeedbackMessage = "Required: Enter a category id to search for";
            }

            return RedirectToPage(new { searchId = searchId});
        }
    }
}

WestWindWatch/WestWindWebApp/Pages/Categories/QueryByPartialDescription.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WestwindSystem.BLL; // for CategoryServices
using WestwindSystem.Entities; // for Category

namespace WestWindWebApp.Pages.Categories
{
    public class QueryByPartialDescriptionModel : PageModel
    {
        // Define a readonly field for CategoryServices
        private readonly CategoryServices _categoryServices;

        public QueryByPartialDescriptionModel(CategoryServices categoryServices)
        {
            _categoryServices = categoryServices;
        }

        public string FeedbackMessage { get; set; }

        [BindProperty(SupportsGet = true)]
        public string Searchvalue { get; set; }

        public List<Category> SearchResultList { get; set; } = new();

        public IActionResult OnPostFetch()
        {
            if (string.IsNullOrWhiteSpace(Searchvalue))
            {
                FeedbackMessage = "Search value is required";
            }
            return RedirectToPage(new { Searchvalue = Searchvalue });
        }

        public IActionResult OnPostClear()
        {
            FeedbackMessage = "";
            SearchResultList.Clear();
            ModelState.Clear();
            return RedirectToPage();
        }

        public void OnGet()
        {
            if (!string.IsNullOrWhiteSpace(Searchvalue))
            {
                SearchResultList = _categoryServices.Category_GetByPartialDescription(Searchvalue);
                if (SearchResultList.Count == 0)
                {
                    FeedbackMessage = "No results returned";
                }
            }
        }
    }
}

WestWindWatch/WestWindWebApp/Pages/Categories/Index.cshtml
@page
@model WestWindWebApp.Pages.Categories.IndexModel
@{
}
<h1>WestWind Categories</h1>

<h2>Table of Categories</h2>
<table>
    <thead>
        <tr>
            <th>CategoryID</th>
            <th>CategoryName</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model.CategoryList)
        {
            <tr>
                <td>@item.CategoryId</td>
                <td>@item.CategoryName</td>
                <td>@item.Description</td>
            </tr>
        }
    </tbody>
</table>

<h2>Menu Option of Categories</h2>
<select>
    @foreach(var item in Model.CategoryList)
    {
        <option value="@item.CategoryId">@item.CategoryName</option>
    }
</select>

<button type="submit">submit</button>

<h2>Category Query by ID</h2>

<h2>Category Query by Partial Description</h2>

WestWindWatch/WestWindWebApp/Pages/Categories/QueryById.cshtml
@page
@model WestWindWebApp.Pages.Categories.QueryByIdModel
@{
}
<h1>Category Query by Primary Key (CategoryID)</h1>

<p>@Model.FeedbackMessage</p>

<p>@Html.Raw(Model.FeedbackMessage)</p> 

<form method="post">
    <label>Enter Category ID:</label>
    <input type="number" asp-for="searchId" placeholder="enter category id here" />

    <button type="submit" asp-page-handler="fetch">Fetch By Id</button>
</form>

<table>
    <thead>
        <tr>
            <th>CategoryID</th>
            <th>CategoryName</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
            @Html.Raw(Model.FeedbackMessage)
    </tbody>
</table>

WestWindWatch/WestWindWebApp/Pages/Categories/QueryByPartialDescription.cshtml
@page
@model WestWindWebApp.Pages.Categories.QueryByPartialDescriptionModel
@{
}
<h1>Category Query by Partial Description</h1>

<p>@Model.FeedbackMessage</p>

<p>@Html.Raw(Model.FeedbackMessage)</p>

@if(Model.SearchResultList.Count > 0)
{
    <table>
        <thead>
            <tr>
                <th>CategoryID</th>
                <th>CategoryName</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model.SearchResultList)
            {
                <tr>
                    <td>@item.CategoryId</td>
                    <td>@item.CategoryName</td>
                    <td>@item.Description</td>
                </tr>
            }
        </tbody>
    </table>
}

<form method="post">
    <label>Enter Category ID:</label>
    <input type="text" asp-for="Searchvalue" placeholder="enter description here" />

    <button type="submit" asp-page-handler="fetch">Fetch By Description</button>
    <button type="submit" asp-page-handler="clear">Clear</button>
</form>