RazorPagesWebAppDemo/Pages/BasicDataManagement.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesWebAppDemo.Pages
{
    public class BasicDataManagementModel : PageModel
    {
        //create bound properties that are directly tied to a control on the form
        //bound properties have the data automatically transferred from the control
        //      into the property
        [BindProperty]
        public int Num { get; set; } //this is tied to the control use the asp-for
        [BindProperty]
        public string FavouriteCourse { get; set; }
        [BindProperty]
        public string Comments { get; set; }
        //Annotation TempData is required IF you are processing multiple requests (OnPost 
        //      followed by OnGet) to retain data within the property
        //[TempData]
        public string FeedBack { get; set; }
        public void OnGet()
        {
            //executes for a Get request
            //the first time the page is requested an automatic Get request is sent
            //execellent "event" to use to do any intialization to your web page display
            //      as the page is shown for the first time
        }
        public void OnPost()
        {
            //process the OnPost request of the form (method="post")
            //the returndatatype can be void or IActionResult
            //OnPost request is the request from a <button> that has NOT indicated a
            //      specific process Post using the asp-page-handler
            //logic that your wish to accomplish should be isolated to the actions
            //  desired for the button
            FeedBack = $"Number {Num}, Course {FavouriteCourse} Comments {Comments}";
        }
        public void OnPostA()
        {
            //process the OnPost request of the form (method="post")
            //this method is called due to the helper-tag on the form button
            //the "string" used on the helper-tag asp-page-handler="string" is
            //   add to the OnPost method name
            FeedBack = $"Button A was pressed";
        }
        public void OnPostB()
        {
            //process the OnPost request of the form (method="post")
            //this method is called due to the helper-tag on the form button
            //the "string" used on the helper-tag asp-page-handler="string" is
            //   add to the OnPost method name
            FeedBack = $"Button B was pressed";
        }
    }
}

RazorPagesWebAppDemo/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace RazorPagesWebAppDemo.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RazorPagesWebAppDemo/Pages/FormFieldControlsUsingTagHelpers.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesWebAppDemo.Pages
{
    public class FormFieldControlsUsingTagHelpersModel : PageModel
    {
        // Define an auto-implemented property for feedback messages
        public string Message { get; set; }
        // Define an auto-implemented property for username
        [BindProperty] // Binds a HTML form field to this property
        public string Username { get; set; }
        // Define an auto-implemented property for password
        [BindProperty]
        public string Password { get; set; }
        // Define an auto-implemented property for confirmed password
        [BindProperty]
        public string ConfirmPassword { get; set; }
        // Create a method to handle a HTTP Post request

        public void OnPost()
        {
            // Check if the Password matches the ConfirmPassword
            if (Password == ConfirmPassword)
            {
                Message = $"You submitted the following: {Username}, {Password}";
            }
            else
            {
                Message = $"The password and confirm password does not match.";
            }
        }
        public void OnGet()
        {
        }
    }
}

RazorPagesWebAppDemo/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesWebAppDemo.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

RazorPagesWebAppDemo/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesWebAppDemo.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RazorPagesWebAppDemo/Pages/formFieldControls.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesWebAppDemo.Pages
{
    public class formFieldControlsModel : PageModel
    {
        // Define an auto-implemented property for feedback messages
        public string Message { get; set; }
        // Define an auto-implemented property for username
        [BindProperty] // Binds a HTML form field to this property
        public string Username { get; set; }
        // Define an auto-implemented property for password
        [BindProperty]
        public string Password { get; set; }
        // Define an auto-implemented property for confirmed password
        [BindProperty]
        public string ConfirmPassword { get; set; }
        // Create a method to handle a HTTP Post request

        public void OnPost()
        {
            // Check if the Password matches the ConfirmPassword
            if(Password == ConfirmPassword)
            {
                Message = $"You submitted the following: {Username}, {Password}";
            }
            else 
            {
                Message = $"The password and confirm password does not match.";
            }
        }
        public void OnGet()
        {
        }
    }
}

RazorPagesWebAppDemo/Pages/hello-world.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesWebAppDemo.Pages
{
    public class hello_worldModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

RazorPagesWebAppDemo/Pages/test-page.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesWebAppDemo.Pages
{
    public class test_pageModel : PageModel
    {
        public string Message { get; set; }

        [BindProperty]
        public string Field { get; set; }
        public void OnGet()
        {
            Message = "OnGet() Method Executed";

        }

        public void OnPost()
        {
            Message = $"OnPost() Method Executed with a file value {Field}";
        }
    }
}

RazorPagesWebAppDemo/Pages/BasicDataManagement.cshtml
@page
@model RazorPagesWebAppDemo.Pages.BasicDataManagementModel
@{
    ViewData["Title"] = "Basic Data Management";
}
<h1>Basic Data Management</h1>
@*
    Investigate using forms on a webpage
    controls: <input> <select> <button> <form> <label> <textarea>
    helper tags: asp-for asp-page-handler
    <form> parameters: method= indicates how data is transfered to server
                                get: visible on Url in plain text
                                post: embedded within the form objects sent to the server
                                      not visible
                       action= directs the server to the page to process form
                               "" directs to current page
                               optional
    <label> no need for parameters, can have helper tags such as asp-for 
            depending on css stylesheet, you can get different results
    <input> used to accept input from the page user
            has various types of acceptable inputs (type=)
            can tie the control to a property on the ModelPage directly (asp-for="propertyname")
    <select> used to display a list of items to select a value
             can be tied to a ModelPage property (asp-for)
             consists of 2 parts on each line in the list of selectable items
             a line of a selectable item is indicated using the <option>
                 <option value="returnedvalue">display text</option>
                 returnedvalue is NOT visible to the page user
                               is the value sent to the ModelPage
                 display text  used by the page user to make the selection
                               is the visible portion of the selection line
            there are times when you wish the use to have a "prompt" in the display list
                this is referred to as the prompt line
                this is NOT a valid value for your data
                it may be used to indicate no choice (a property can be nullable, handled logically)
    <textarea> display a large text input box area for the web page user to
                  enter a large amount of data
               display size is controlled using rows= (vertical) and cols= (horizontal)
               auto-scroll bars
    <button>  three types (type=)
                 submit: sends the form to the server for processing
                 reset:  locally clear the form and does NOT send to server for processing
                 button: 
              you can assign a specific value associated with the button that can be
                 logically tested in your ModelPage (value=) (optional)
              to identify the contol you can use (optional)
                 id= basically used by javascript to identify the control
                 name= is used by the Request["xxx"] to identify the control in your C# code
                 values can be the same
              helper tag to identifer processing OnPost on the ModelPage (asp-page-helper)
*@
<form method="post">
    <label>
        Enter a number <input type="number" asp-for="Num" />
    </label>
    <label>
        Select a favourite course; (drop down list)
        <select asp-for="FavouriteCourse">
            <option value="">select ...</option>
            <option value="1008">COMP1008</option>
            <option value="1517">CPSC1517</option>
            <option value="2018">DMIT2018</option>
            <option value="1525">ANAP1525</option>
        </select>
    </label>
    <label>
        Comments
        <textarea asp-for="Comments" rows="5" cols="100"></textarea>
    </label>
    <br/>
    <button type="submit" value="uniquevalueA" id="jsIdentifier"
            name="RequestObjectIdentifier" asp-page-handler="A">
            Press Me A (submit form)
        </button>
            &nbsp;&nbsp;
    <button type="submit" value="uniquevalueB" id="jsIdentifier"
            name="RequestObjectIdentifier" asp-page-handler="B">
            Press Me B (submit form)
       </button>
            &nbsp;&nbsp;
    <button type="submit" value="uniquevalueX" id="jsIdentifier"
            name="RequestObjectIdentifier" >
            Press Me (submit form)
       </button>
</form>
<br/>
<p>@Model.FeedBack</p>

RazorPagesWebAppDemo/Pages/FormFieldControlsUsingTagHelpers.cshtml
@page
@model RazorPagesWebAppDemo.Pages.FormFieldControlsUsingTagHelpersModel
@{
    ViewData["Title"] = "Form Fields Using Tag Helpers";
}
<h1>HTML Form Field Controls</h1>
@Model.Message
<form method="post">
    <div>
        <label asp-for=Username />
        <input asp-for=Username />
    </div>

    <div>
        <label asp-for=Password />
        <input asp-for=Password type="password"/>
    </div>

    <div>
        <label asp-for=ConfirmPassword />
        <input asp-for=ConfirmPassword type="password"/>
    </div>

    <div>
        <button type="submit">Submit</button>
    </div>

</form>

RazorPagesWebAppDemo/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorPagesWebAppDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/holiday.css@0.9.8" />
    <link rel="stylesheet" href="~/RazorPagesWebAppDemo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RazorPagesWebAppDemo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/test-page">Test Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/BasicDataManagement">BasicDataManagement</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RazorPagesWebAppDemo - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RazorPagesWebAppDemo/Pages/formFieldControls.cshtml
@page
@model RazorPagesWebAppDemo.Pages.formFieldControlsModel
@{
    ViewData["Title"] = "HTML Form Field Controls";
}
<h1>HTML Form Field Controls</h1>
@Model.Message
<form method="post">
    <div>
        <label for="Username">Username</label>
        <input type="text" id="Username" name="Username" value="@Model.Username"/>
    </div>

    <div>
        <label for="Password">Password</label>
        <input type="password" id="Password" name="Password" value="@Model.Password"/>
    </div>

    <div>
        <label for="Password">Confirm Password</label>
        <input type="password" id="ConfirmPassword" name="ConfirmPassword" value="@Model.ConfirmPassword"/>
    </div>

    <div>
        <button type="submit">Submit</button>
    </div>

</form>

RazorPagesWebAppDemo/Pages/hello-world.cshtml
@page
@model RazorPagesWebAppDemo.Pages.hello_worldModel
@{
}
<h1>Hello World from a Razor Page</h1>
<p>Current date is @DateTime.Now</p>
@for(int i = 0; i <= 10; i++)
{
    string fontSize = 15 + i + "px"; 
    <p style="font-size: @fontSize">Hello World</p>
}

RazorPagesWebAppDemo/Pages/test-page.cshtml
@page
@model RazorPagesWebAppDemo.Pages.test_pageModel
@{
    ViewData["Title"] = "Test Page";
}
<h1>Test Page</h1>

@Model.Message
<form name="TestPageForm" method="post">
    <div>
        <label for="field">Field: </label>
        <input type="text" id="field" name="Field" />
    </div>
    <div>
        <button type="submit">Submit</button>
    </div>
</form>